# Default values for ignite.
replicaCount: 1

kubernetesClusterDomain: cluster.local

image:
  repository: apacheignite/ignite
  tag: 2.16.0-jdk11
  pullPolicy: IfNotPresent
# If imagePullSecrets needed remove {} and uncomment below to set your secret name
imagePullSecrets: {}
  # - name: <your-image-pull-secret>

# Chart name override
nameOverride: ""
# Fullname override
fullnameOverride: ""
# Fullname suffix (won't work together with fullnameOverride)
fullnameSuffix: ""

persistence:
  enabled: true
  size: 2Gi
  provisioner: cluster.local/nfs-subdir-external-provisioner
  provisioner_parameters:
          archiveOnDelete: "true"

wal_persistence:
  enabled: true
  size: 2Gi
  provisioner: cluster.local/nfs-subdir-external-provisioner
  provisioner_parameters:
          archiveOnDelete: "true"

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# Service configuration for Ignite metrics
metrics:
  enabled: true
  # TODO: ClusterIP and Loadbalancer option will be added.
  # If metrics enabled, you can specify a NodePort value below.
  service:
    type: NodePort
    port: 9404
    nodePort: null

jmx_exporter:
  image:
    # Default image for jmx-exporter init container
    repository: busybox
    tag: 1.36
    pullPolicy: IfNotPresent

nodeSelector: {}

tolerations: []

affinity: {}
